### ISSUE TITLE
koa deprecated Support for generators

### ISSUE THREAD

**Issue by chrisdothtml** [vgno/koa-add-trailing-slashes#1]
> koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md

**Comment by dlmr** [comment]
So sorry for missing this issue completely. Thanks for reporting it!

Will update it soon, sorry again for the delay!

**Comment by dlmr** [comment]
Closed through #2 and released in `2.0.0`.
